encoding: utf-8
timezone: Europe/Stockholm
exclude: [LICENSE, README.md, Gemfile, Gemfile.lock]
permalink: /:categories/:year/:month/:title/
languages: [en, sv]
nav: [home, about]
url: http://hexagenic.net
relative_permalinks: false

solarizedTheme: dark

author:
  full_name: Mattias Hermansson
  email: hexagenic@gmail.com
  gplus: https://www.google.com/+MattiasHermanssonHexagenic

# Scopes

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: posts
    values:
      type: posts

  - scope:
      path: ""
      type: pages
    values:
      type: pages

  - scope:
      path: _posts/ja
    values:
      lang: ja

  - scope:
      path: _posts/en
    values:
      lang: en

  - scope:
      path: _posts/sv
    values:
      lang: sv

# Generators

highlighter: pygments
sass:
  style: :compressed

markdown: kramdown
kramdown:
  header_offset: 2

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

#gems:
#  - jekyll-redirect-from
#  - jemoji
